# Generated by Django 3.2.4 on 2021-06-14 07:26

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vtypeengine',
            name='Vtype',
        ),
        migrations.AddField(
            model_name='car',
            name='yearEdition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vtypeengine',
            name='VType',
            field=models.ForeignKey(blank=True, limit_choices_to=api.models.VTypeEngine.choice, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.engine'),
        ),
    ]
