# Generated by Django 3.2.3 on 2021-06-12 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.brand'),
        ),
        migrations.AlterField(
            model_name='car',
            name='driveType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.drivetype'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engines',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.engine'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuelType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fueltype'),
        ),
        migrations.AlterField(
            model_name='car',
            name='highLight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='hoursePower',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.origin'),
        ),
        migrations.AlterField(
            model_name='car',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.segment'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tireSize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tiresize'),
        ),
        migrations.AlterField(
            model_name='car',
            name='torque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
