# Generated by Django 3.2.4 on 2021-06-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_vtypeengine_vtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vtypeengine',
            old_name='Vtype',
            new_name='VType',
        ),
        migrations.RemoveField(
            model_name='car',
            name='tireSize',
        ),
        migrations.AddField(
            model_name='car',
            name='yearEdition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='TireSize',
        ),
    ]
