# Generated by Django 3.2.3 on 2021-06-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_car_engine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='engine',
            new_name='engines',
        ),
    ]
