# Generated by Django 3.2.3 on 2021-06-22 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210622_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='engineType',
            new_name='engine',
        ),
    ]
