# Generated by Django 3.2.5 on 2021-08-02 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_car_accuracy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='accuracy',
        ),
    ]
