# Generated by Django 3.1.7 on 2021-04-29 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.CharField(max_length=500)),
                ('hoursePower', models.CharField(max_length=1000)),
                ('torque', models.CharField(max_length=1000)),
                ('highLight', models.CharField(max_length=1000)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brands')),
            ],
        ),
        migrations.CreateModel(
            name='DriveTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Engines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FuelTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Origins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Segments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TireSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
        migrations.AddField(
            model_name='cars',
            name='driveType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.drivetypes'),
        ),
        migrations.AddField(
            model_name='cars',
            name='engines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.engines'),
        ),
        migrations.AddField(
            model_name='cars',
            name='fueltype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fueltypes'),
        ),
        migrations.AddField(
            model_name='cars',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.origins'),
        ),
        migrations.AddField(
            model_name='cars',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.segments'),
        ),
        migrations.AddField(
            model_name='cars',
            name='tireSize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tiresize'),
        ),
    ]
