# Generated by Django 3.1.7 on 2021-04-29 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210429_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.CharField(max_length=500)),
                ('hoursePower', models.CharField(max_length=1000)),
                ('torque', models.CharField(max_length=1000)),
                ('highLight', models.CharField(max_length=1000)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brand')),
            ],
        ),
        migrations.CreateModel(
            name='DriveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='cars',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='driveType',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='engines',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='fueltype',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='tireSize',
        ),
        migrations.DeleteModel(
            name='Brands',
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
        migrations.DeleteModel(
            name='DriveTypes',
        ),
        migrations.DeleteModel(
            name='Engines',
        ),
        migrations.DeleteModel(
            name='FuelTypes',
        ),
        migrations.DeleteModel(
            name='Origins',
        ),
        migrations.DeleteModel(
            name='Segments',
        ),
        migrations.AddField(
            model_name='car',
            name='driveType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.drivetype'),
        ),
        migrations.AddField(
            model_name='car',
            name='engines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.engine'),
        ),
        migrations.AddField(
            model_name='car',
            name='fueltype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fueltype'),
        ),
        migrations.AddField(
            model_name='car',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.origin'),
        ),
        migrations.AddField(
            model_name='car',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.segment'),
        ),
        migrations.AddField(
            model_name='car',
            name='tireSize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tiresize'),
        ),
    ]
