# Generated by Django 3.1.7 on 2021-05-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210429_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='fueltype',
            new_name='fuelType',
        ),
    ]
